config/routes.rb
AppBasurero::Application.routes.draw do
  resources :tables


  resources :users


  resources :roles


  resources :employees


  resources :jobs


  resources :product_types


  resources :brands


  #resources :subcategories, only: [:edit, :delete, :show]
  get "/subcategories/:id" => "subcategories#index", as: :subcategories
  post "/subcategories/:id" => "subcategories#create", as: :subcategory
  get "/subcategories/new/:id" => "subcategories#new", as: :new_subcategory
  get "/subcategories/show/:id" => "subcategories#show", as: :show_subcategory
  get "/subcategories/:id/edit" => "subcategories#edit", as: :edit_subcategory
  put "/subcategories/:id" => "subcategories#update", as: :subcategory
  delete "/subcategories/:id" => "subcategories#destroy", as: :subcategory

  resources :categories

  get "main/index"

  root to: "main#index"
  	
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories
  attr_accessible :description, :name
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :employees
  attr_accessible :name
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :job
  belongs_to :country
  has_one :user
  attr_accessible :address, :document, :document_type, :email, :first_name, :country_id,
  								:gender, :last_name, :nit, :state, :job_id, :user_attributes
  accepts_nested_attributes_for :user
end

app/models/job.rb
class Job < ActiveRecord::Base
	has_many :employees
  attr_accessible :description, :name
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :description, :name, :role_id
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  attr_accessible :description, :name, :category_id
end

app/models/table.rb
class Table < ActiveRecord::Base
  attr_accessible :identifier, :location, :state
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :employee
  belongs_to :role
  attr_accessible :password, :state, :username
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_types }
    end
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_type }
    end
  end

  # GET /product_types/new
  # GET /product_types/new.json
  def new
    @product_type = ProductType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_type }
    end
  end

  # GET /product_types/1/edit
  def edit
    @product_type = ProductType.find(params[:id])
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(params[:product_type])

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'El tipo de producto fue creado.' }
        format.json { render json: @product_type, status: :created, location: @product_type }
      else
        format.html { render action: "new" }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_types/1
  # PUT /product_types/1.json
  def update
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      if @product_type.update_attributes(params[:product_type])
        format.html { redirect_to @product_type, notice: 'El tipo de producto fue actualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type = ProductType.find(params[:id])
    @product_type.destroy

    respond_to do |format|
      format.html { redirect_to product_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/subcategory_helper.rb
module SubcategoryHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_types/_form.html.erb
<%= form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h2>Editar tipo de producto</h2>

<%= render 'form' %>

<%= link_to 'Ver', @product_type, class: "btn btn-primary" %> |
<%= link_to 'Atras', product_types_path, class: "btn btn-primary" %>

app/views/product_types/index.html.erb
<h1>Lista de tipo de productos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripci&oacute;n</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @product_types.each do |product_type| %>
  <tbody>
    <tr>
      <td><%= product_type.name %></td>
      <td><%= product_type.description %></td>
      <td><%= link_to 'Ver', product_type %></td>
      <td><%= link_to 'Editar', edit_product_type_path(product_type) %></td>
      <td><%= link_to 'Eliminar', product_type, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
    </tr>
  </tbody>
<% end %>
</table>

<br />

<%= link_to 'New tipo de producto', new_product_type_path, class: "btn btn-primary" %>

app/views/product_types/new.html.erb
<h2>Nuevo tipo de producto</h2>

<%= render 'form' %>

<%= link_to 'Atras', product_types_path, class: "btn btn-primary" %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @product_type.name %>
</p>

<p>
  <b>Descripci&oacute;n:</b>
  <%= @product_type.description %>
</p>


<%= link_to 'Editar', edit_product_type_path(@product_type), class: "btn btn-primary" %> |
<%= link_to 'Atras', product_types_path, class: "btn btn-primary" %>