config/routes.rb
AppBasurero::Application.routes.draw do
  resources :tables


  resources :users


  resources :roles


  resources :employees


  resources :jobs


  resources :product_types


  resources :brands


  #resources :subcategories, only: [:edit, :delete, :show]
  get "/subcategories/:id" => "subcategories#index", as: :subcategories
  post "/subcategories/:id" => "subcategories#create", as: :subcategory
  get "/subcategories/new/:id" => "subcategories#new", as: :new_subcategory
  get "/subcategories/show/:id" => "subcategories#show", as: :show_subcategory
  get "/subcategories/:id/edit" => "subcategories#edit", as: :edit_subcategory
  put "/subcategories/:id" => "subcategories#update", as: :subcategory
  delete "/subcategories/:id" => "subcategories#destroy", as: :subcategory

  resources :categories

  get "main/index"

  root to: "main#index"
  	
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories
  attr_accessible :description, :name
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :employees
  attr_accessible :name
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :job
  belongs_to :country
  has_one :user
  attr_accessible :address, :document, :document_type, :email, :first_name, :country_id,
  								:gender, :last_name, :nit, :state, :job_id, :user_attributes
  accepts_nested_attributes_for :user
end

app/models/job.rb
class Job < ActiveRecord::Base
	has_many :employees
  attr_accessible :description, :name
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :description, :name, :role_id
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  attr_accessible :description, :name, :category_id
end

app/models/table.rb
class Table < ActiveRecord::Base
  attr_accessible :identifier, :location, :state
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :employee
  belongs_to :role
  attr_accessible :password, :state, :username
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'El cargo de trabajo fue creado.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'EL cargo de trabajo fue actualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'El rol fue creado.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'El rol fue actulizado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/subcategory_helper.rb
module SubcategoryHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>  
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label "Nombre" %>
    <%= f.text_field :name, class: "input-xlarge" %>
  </div>      
  
  <div class="control-group">
    <%= f.label "Descripcion" %>
    <%= f.text_area :description, rows: "5", class: "input-xxlarge" %>
  </div>      
 
  <div class="control-group">
    <%= f.button "Guardar", class: "btn", type: "submit" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h2>Editar cargo</h2>
<%= render 'form' %>

<%= link_to 'Ver', @job, class: "btn btn-primary" %> |
<%= link_to 'Atras', jobs_path, class: "btn btn-primary" %>

app/views/jobs/index.html.erb
<h1>Listado de cargos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripci&oacute;n</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @jobs.each do |job| %>
  <tbody>
    <tr>
      <td><%= job.name %></td>
      <td><%= job.description %></td>
      <td><%= link_to 'Ver', job %></td>
      <td><%= link_to 'Editar', edit_job_path(job) %></td>
      <td><%= link_to 'Eliminar', job, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
    </tr>
  </tbody>
<% end %>
</table>

<br />

<%= link_to 'Nueva cargo', new_job_path, class: "btn btn-primary" %>

app/views/jobs/new.html.erb
<h2>Nuevo cargo</h2>
<%= render 'form' %>

<%= link_to 'Atras', jobs_path, class: "btn btn-primary" %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @job.name %>
</p>

<p>
  <b>Descripci&oacute;n:</b>
  <%= @job.description %>
</p>


<%= link_to 'Editar', edit_job_path(@job), class: "btn btn-primary" %> |
<%= link_to 'Atras', jobs_path, class: "btn btn-primary" %>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label "Nombre" %>
    <%= f.text_field :name, class: "input-xlarge" %>
  </div>      
  
  <div class="control-group">
    <%= f.label "Descripcion" %>
    <%= f.text_area :description, rows: "5", class: "input-xxlarge" %>
  </div>      
 
  <div class="control-group">
    <%= f.button "Guardar", class: "btn", type: "submit" %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h2>Editar rol</h2>

<%= render 'form' %>

<%= link_to 'Ver', @role, class: "btn btn-primary" %> |
<%= link_to 'Atras', roles_path, class: "btn btn-primary" %>

app/views/roles/index.html.erb
<h1>Lista de roles</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripci&oacute;n</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @roles.each do |role| %>
  <tbody>
    <tr>
      <td><%= role.name %></td>
      <td><%= role.description %></td>
      <td><%= link_to 'Ver', role %></td>
      <td><%= link_to 'Editar', edit_role_path(role) %></td>
      <td><%= link_to 'Eliminar', role, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
    </tr>
  </tbody>
<% end %>
</table>

<br />

<%= link_to 'Nuevo rol', new_role_path, class: "btn btn-primary" %>

app/views/roles/new.html.erb
<h2>Nuevo rol</h2>

<%= render 'form' %>

<%= link_to 'Atras', roles_path, class: "btn btn-primary" %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @role.name %>
</p>

<p>
  <b>Descripci&oacute;n:</b>
  <%= @role.description %>
</p>


<%= link_to 'Editar', edit_role_path(@role), class: "btn btn-primary" %> |
<%= link_to 'Atras', roles_path, class: "btn btn-primary" %>